use-sort:
    group:
        - _main
        - Sod
    group-type: each
    sort-type: alph
    sort-direction: asc

header: |
    /*
     * This file is part of the BlogBundle package.
     *
     * Copyright (c) daniel@desarrolla2.com
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     *
     * @author Daniel González <daniel@desarrolla2.com>
     */