<?php

namespace Desarrolla2\Bundle\BlogBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Desarrolla2\Bundle\BlogBundle\Model\LinkStatus;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository {

    /**
     * 
     * @param type $limit
     * @return array
     */
    public function getActive() {
        $query = $this->getQueryForGetActive();
        return $query->getResult();
    }

    /**
     * 
     * @return \Doctrine\ORM\Query
     */
    public function getQueryForGetActive() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                ' SELECT l FROM BlogBundle:Link l ' .
                ' WHERE l.isPublished = ' . LinkStatus::PUBLISHED .
                ' ORDER BY l.createdAt DESC '
                )
        ;
        return $query;
    }

    /**
     * 
     * @param type $limit
     * @return array
     */
    public function getActiveOrdered() {
        $query = $this->getQueryForGetActiveOrdered();
        return $query->getResult();
    }

    /**
     * 
     * @return \Doctrine\ORM\Query
     */
    public function getQueryForGetActiveOrdered() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                ' SELECT l FROM BlogBundle:Link l ' .
                ' WHERE l.isPublished = ' . LinkStatus::PUBLISHED .
                ' ORDER BY l.name ASC '
                )
        ;
        return $query;
    }

    /**
     * 
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilderForFilter() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb
                ->select('p')
                ->from('BlogBundle:Link', 'p')
                ->orderBy('p.updatedAt', 'DESC')
        ;
        return $qb;
    }

}
