<?php

/*
 * This file is part of the BlogBundle package.
 *
 * Copyright (c) daniel@desarrolla2.com
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * @author Daniel González <daniel@desarrolla2.com>
 */

namespace Desarrolla2\Bundle\BlogBundle\Entity\Repository;

use DateTime;
use Desarrolla2\Bundle\BlogBundle\Entity\Post;
use Desarrolla2\Bundle\BlogBundle\Entity\PostClick;
use Doctrine\ORM\EntityRepository;

/**
 * PostClickRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostClickRepository extends EntityRepository
{
    /**
     * @param Post $post
     */
    public function add(Post $post)
    {
        $em = $this->getEntityManager();

        $date = new DateTime();

        $click = $this->findOneBy(
            array(
                'post_id' => $post->getId(),
                'date' => $date,
            )
        );
        if (!$click) {
            $click = new PostClick();
            $click->setPost($post);
            $click->setDate($date);
        }

        $click->increment();

        $em->persist($click);
        $em->flush();
    }
}
